# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GPS.proto',
  package='gps',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tGPS.proto\x12\x03gps\"\x16\n\x07GpsList\x12\x0b\n\x03gps\x18\x01 \x03(\x0c\"t\n\tSourceMap\x12*\n\x06source\x18\x01 \x03(\x0b\x32\x1a.gps.SourceMap.SourceEntry\x1a;\n\x0bSourceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.gps.GpsList:\x02\x38\x01\"\x93\x01\n\x06GpsMap\x12)\n\x07gpsinfo\x18\x01 \x03(\x0b\x32\x18.gps.GpsMap.GpsinfoEntry\x12\x0e\n\x06\x63\x61rNum\x18\x02 \x01(\x05\x12\x0e\n\x06gpsNum\x18\x03 \x01(\x05\x1a>\n\x0cGpsinfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.gps.SourceMap:\x02\x38\x01\x62\x06proto3')
)




_GPSLIST = _descriptor.Descriptor(
  name='GpsList',
  full_name='gps.GpsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps', full_name='gps.GpsList.gps', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=40,
)


_SOURCEMAP_SOURCEENTRY = _descriptor.Descriptor(
  name='SourceEntry',
  full_name='gps.SourceMap.SourceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gps.SourceMap.SourceEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gps.SourceMap.SourceEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=158,
)

_SOURCEMAP = _descriptor.Descriptor(
  name='SourceMap',
  full_name='gps.SourceMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='gps.SourceMap.source', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SOURCEMAP_SOURCEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=158,
)


_GPSMAP_GPSINFOENTRY = _descriptor.Descriptor(
  name='GpsinfoEntry',
  full_name='gps.GpsMap.GpsinfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gps.GpsMap.GpsinfoEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gps.GpsMap.GpsinfoEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=308,
)

_GPSMAP = _descriptor.Descriptor(
  name='GpsMap',
  full_name='gps.GpsMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpsinfo', full_name='gps.GpsMap.gpsinfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carNum', full_name='gps.GpsMap.carNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsNum', full_name='gps.GpsMap.gpsNum', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GPSMAP_GPSINFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=308,
)

_SOURCEMAP_SOURCEENTRY.fields_by_name['value'].message_type = _GPSLIST
_SOURCEMAP_SOURCEENTRY.containing_type = _SOURCEMAP
_SOURCEMAP.fields_by_name['source'].message_type = _SOURCEMAP_SOURCEENTRY
_GPSMAP_GPSINFOENTRY.fields_by_name['value'].message_type = _SOURCEMAP
_GPSMAP_GPSINFOENTRY.containing_type = _GPSMAP
_GPSMAP.fields_by_name['gpsinfo'].message_type = _GPSMAP_GPSINFOENTRY
DESCRIPTOR.message_types_by_name['GpsList'] = _GPSLIST
DESCRIPTOR.message_types_by_name['SourceMap'] = _SOURCEMAP
DESCRIPTOR.message_types_by_name['GpsMap'] = _GPSMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpsList = _reflection.GeneratedProtocolMessageType('GpsList', (_message.Message,), dict(
  DESCRIPTOR = _GPSLIST,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:gps.GpsList)
  ))
_sym_db.RegisterMessage(GpsList)

SourceMap = _reflection.GeneratedProtocolMessageType('SourceMap', (_message.Message,), dict(

  SourceEntry = _reflection.GeneratedProtocolMessageType('SourceEntry', (_message.Message,), dict(
    DESCRIPTOR = _SOURCEMAP_SOURCEENTRY,
    __module__ = 'GPS_pb2'
    # @@protoc_insertion_point(class_scope:gps.SourceMap.SourceEntry)
    ))
  ,
  DESCRIPTOR = _SOURCEMAP,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:gps.SourceMap)
  ))
_sym_db.RegisterMessage(SourceMap)
_sym_db.RegisterMessage(SourceMap.SourceEntry)

GpsMap = _reflection.GeneratedProtocolMessageType('GpsMap', (_message.Message,), dict(

  GpsinfoEntry = _reflection.GeneratedProtocolMessageType('GpsinfoEntry', (_message.Message,), dict(
    DESCRIPTOR = _GPSMAP_GPSINFOENTRY,
    __module__ = 'GPS_pb2'
    # @@protoc_insertion_point(class_scope:gps.GpsMap.GpsinfoEntry)
    ))
  ,
  DESCRIPTOR = _GPSMAP,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:gps.GpsMap)
  ))
_sym_db.RegisterMessage(GpsMap)
_sym_db.RegisterMessage(GpsMap.GpsinfoEntry)


_SOURCEMAP_SOURCEENTRY._options = None
_GPSMAP_GPSINFOENTRY._options = None
# @@protoc_insertion_point(module_scope)
